version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 200000000fia
- name: bob
  coins:
  - 100000000fia
genesis:
  chain_id: fiamma-testnet-1
  app_state:
    staking:
      params:
        bond_denom: fia
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5fia
validators:
- name: alice
  bonded: 100000000fia
build:
  main: cmd/fiammad
