version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 2000000000000ufia
- name: bob
  coins:
  - 1000000000000ufia
genesis:
  chain_id: fiamma-testnet-1
  app_state:
    staking:
      params:
        bond_denom: ufia
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5fia
validators:
- name: alice
  bonded: 1000000000ufia
build:
  main: cmd/fiammad
