version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 200000000fiamma
- name: bob
  coins:
  - 100000000fiamma
genesis:
  chain_id: fiamma-testnet-1
  app_state:
    staking:
      params:
        bond_denom: fiamma
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5fiamma
validators:
- name: alice
  bonded: 100000000fiamma
build:
  main: cmd/fiammad

