version: "3.2"

services:
  node-setup:
    image: ghcr.io/fiamma-chain/fiamma
    build:
      context: ../../
      dockerfile: ../../Dockerfile
    volumes:
      - ../testnet-nodes/${NODE_NAME}:/root/.fiamma
      - ../setup_node.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME}

  validator-setup:
    image: ghcr.io/fiamma-chain/fiamma
    build:
      context: ../../
      dockerfile: ../../Dockerfile
    volumes:
      - ../testnet-nodes/${NODE_NAME}:/root/.fiamma
      - ../setup_validator.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME} 1000000fiamma

  validator-runner:
    image: ghcr.io/fiamma-chain/fiamma
    build:
      context: ../../
      dockerfile: ../../Dockerfile
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - ../testnet-nodes/${NODE_NAME}:/root/.fiamma
    command: start
