// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fiamma/zkproof/query.proto

package zkproof

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName             = "/fiamma.zkproof.Query/Params"
	Query_PendingProof_FullMethodName       = "/fiamma.zkproof.Query/PendingProof"
	Query_PendingProofByType_FullMethodName = "/fiamma.zkproof.Query/PendingProofByType"
	Query_AllProofTypes_FullMethodName      = "/fiamma.zkproof.Query/AllProofTypes"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of PendingProof items.
	PendingProof(ctx context.Context, in *QueryPendingProofRequest, opts ...grpc.CallOption) (*QueryPendingProofResponse, error)
	// Queries a list of PendingProofByType items.
	PendingProofByType(ctx context.Context, in *QueryPendingProofByTypeRequest, opts ...grpc.CallOption) (*QueryPendingProofByTypeResponse, error)
	// Queries a list of AllProofTypes items.
	AllProofTypes(ctx context.Context, in *QueryAllProofTypesRequest, opts ...grpc.CallOption) (*QueryAllProofTypesResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingProof(ctx context.Context, in *QueryPendingProofRequest, opts ...grpc.CallOption) (*QueryPendingProofResponse, error) {
	out := new(QueryPendingProofResponse)
	err := c.cc.Invoke(ctx, Query_PendingProof_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingProofByType(ctx context.Context, in *QueryPendingProofByTypeRequest, opts ...grpc.CallOption) (*QueryPendingProofByTypeResponse, error) {
	out := new(QueryPendingProofByTypeResponse)
	err := c.cc.Invoke(ctx, Query_PendingProofByType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllProofTypes(ctx context.Context, in *QueryAllProofTypesRequest, opts ...grpc.CallOption) (*QueryAllProofTypesResponse, error) {
	out := new(QueryAllProofTypesResponse)
	err := c.cc.Invoke(ctx, Query_AllProofTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of PendingProof items.
	PendingProof(context.Context, *QueryPendingProofRequest) (*QueryPendingProofResponse, error)
	// Queries a list of PendingProofByType items.
	PendingProofByType(context.Context, *QueryPendingProofByTypeRequest) (*QueryPendingProofByTypeResponse, error)
	// Queries a list of AllProofTypes items.
	AllProofTypes(context.Context, *QueryAllProofTypesRequest) (*QueryAllProofTypesResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) PendingProof(context.Context, *QueryPendingProofRequest) (*QueryPendingProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingProof not implemented")
}
func (UnimplementedQueryServer) PendingProofByType(context.Context, *QueryPendingProofByTypeRequest) (*QueryPendingProofByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingProofByType not implemented")
}
func (UnimplementedQueryServer) AllProofTypes(context.Context, *QueryAllProofTypesRequest) (*QueryAllProofTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllProofTypes not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingProof(ctx, req.(*QueryPendingProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingProofByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingProofByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingProofByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingProofByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingProofByType(ctx, req.(*QueryPendingProofByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllProofTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllProofTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllProofTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllProofTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllProofTypes(ctx, req.(*QueryAllProofTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fiamma.zkproof.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PendingProof",
			Handler:    _Query_PendingProof_Handler,
		},
		{
			MethodName: "PendingProofByType",
			Handler:    _Query_PendingProofByType_Handler,
		},
		{
			MethodName: "AllProofTypes",
			Handler:    _Query_AllProofTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fiamma/zkproof/query.proto",
}
